name: advent-of-code-y2025
version: 0.1.0.0
github: glebec/advent-of-code-y2025
license: BSD3
author: Gabriel Lebec
maintainer: glebec@gmail.com
copyright: 2025 Gabriel Lebec
description: Please see the README on GitHub at <https://github.com/glebec/advent-of-code-y2025#readme>
# synopsis: Short description of your package
# category: Web

extra-source-files:
    - README.md

dependencies:
    - base >= 4.9.1 && < 5
    - containers >= 0.6.8
    - data-interval
    - megaparsec
    - raw-strings-qq
    - split

default-extensions:
    - BangPatterns
    - ConstraintKinds
    - DeriveFoldable
    - DeriveFunctor
    - DeriveGeneric
    - DeriveLift
    - DeriveTraversable
    - DerivingStrategies
    - DerivingVia
    - EmptyCase
    - FlexibleContexts
    - FlexibleInstances
    - GeneralizedNewtypeDeriving
    - ImportQualifiedPost
    - InstanceSigs
    - KindSignatures
    - LambdaCase
    - MultiParamTypeClasses
    - OverloadedStrings
    - NamedFieldPuns
    - RankNTypes
    - ScopedTypeVariables
    - StandaloneDeriving
    - TupleSections
    - TypeApplications
    - TypeOperators

ghc-options:
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints

library:
    source-dirs: src

tests:
    advent-of-code-y2025-test:
        main: Spec.hs
        source-dirs: test
        dependencies:
            - advent-of-code-y2025
            - hspec
            # - hedgehog
            # - QuickCheck
